name: Build with PyInstaller to main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install lxml==4.9.1 --only-binary=lxml
        pip install libxml2-python3 libxslt
        pip install -r requirements.txt
        pip install pysimplegui
        pip install pyinstaller
        pip list

    - name: Increment version
      id: increment_version
      run: |
        # Use PowerShell commands to read and increment the version
        $version = Get-Content exe_version.txt
        $major, $minor = $version -split "\."
        $minor = [int]$minor + 1
        $new_version = "$major.$minor"
        $new_version > exe_version.txt
        echo "::set-output name=new_version::$new_version"

        
    - name: Build with PyInstaller
      run: pyinstaller --name cfd_report_gen${{ steps.increment_version.outputs.new_version }} --onefile -w auto_report.py

    - name: Build Charts module with PyInstaller
      run: pyinstaller --name cfd_charts_gen${{ steps.increment_version.outputs.new_version }} --onefile -w run_only_charts.py
        
    - name: List files in dist directory
      run: dir .\dist
      
    - name: Commit and push artifact and version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add exe_version.txt
        git add dist/cfd_report_gen${{ steps.increment_version.outputs.new_version }}.exe -f
        git add dist/cfd_charts_gen${{ steps.increment_version.outputs.new_version }}.exe -f
        git commit -m "updated version"
        git push